
app = "<APP_NAME>"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  url = "<APP_URL>"
  port=8080  
  database__client = "sqlite3"  
  database__connection__filename = "content/data/ghost.db"  
  database__useNullAsDefault = "true"  
  database__debug = "false"
  storage__active = "s3"
  storage__s3__accessKeyId= "<AWS_S3_KEY_ID>"
  storage__s3__secretAccessKey= "<AWS_S3_ACCES_KEY>"
  storage__s3__region= "us-east-1"
  storage__s3__bucket= "<S3_BUCKET_NAME>"
  storage__s3__assetHost= "<CLOUDFRONT_URL>"

[mounts]
  source="data"
  destination="/var/lib/ghost/content"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2368
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
